// Field definitions shared by the admin UI (renders forms) and the API (validates input).
// Keep this file free of server-only imports.

export const METALS = ["22K Gold", "18K Gold", "Diamond", "Platinum", "Silver"];
export const PAGE_GROUPS = ["About", "Jewellery Guide", "Media", "Policies", "Quick Links"];

export const resources = {
  products: {
    label: "Products",
    singular: "Product",
    slugFrom: "name",
    sort: { order: 1, createdAt: -1 },
    columns: [
      { name: "image", type: "image" },
      { name: "name", label: "Name" },
      { name: "collection", label: "Category", type: "ref", ref: "categories" },
      { name: "metal", label: "Metal" },
      { name: "price", label: "Price", type: "price" },
      { name: "featured", label: "Featured", type: "bool" },
      { name: "active", label: "Visible", type: "bool" },
    ],
    filter: { name: "collection", ref: "categories", label: "All categories" },
    fields: [
      { name: "name", label: "Product name", type: "text", required: true },
      { name: "collection", label: "Category", type: "ref", ref: "categories", required: true },
      { name: "image", label: "Main image", type: "image", required: true },
      { name: "gallery", label: "More images", type: "images", help: "Optional extra photos shown on the product page." },
      { name: "metal", label: "Metal / type", type: "text", suggestions: METALS, default: "22K Gold" },
      { name: "weight", label: "Weight (e.g. 8.50 g)", type: "text" },
      { name: "price", label: "Price (₹)", type: "number", help: "Leave 0 to show “Price on request”." },
      { name: "mrp", label: "MRP / strike-through price (₹)", type: "number", help: "Optional. Leave 0 to hide." },
      { name: "code", label: "Product code", type: "text" },
      { name: "description", label: "Description", type: "textarea", rows: 5 },
      { name: "featured", label: "Show on home page (Featured Designs)", type: "boolean" },
      { name: "active", label: "Visible on website", type: "boolean", default: true },
      { name: "order", label: "Sort priority (lower shows first)", type: "number", default: 0 },
    ],
  },
  categories: {
    label: "Categories",
    singular: "Category",
    slugFrom: "title",
    sort: { order: 1, createdAt: 1 },
    columns: [
      { name: "image", type: "image" },
      { name: "title", label: "Title" },
      { name: "slug", label: "URL" },
      { name: "order", label: "Order" },
      { name: "active", label: "Visible", type: "bool" },
    ],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "blurb", label: "Short description", type: "textarea", rows: 2 },
      { name: "image", label: "Image", type: "image", required: true, help: "Used on the home page tile and the category banner." },
      { name: "order", label: "Menu order (lower first)", type: "number", default: 100 },
      { name: "active", label: "Visible on website", type: "boolean", default: true },
    ],
  },
  offers: {
    label: "Offers",
    singular: "Offer",
    sort: { order: 1, createdAt: -1 },
    columns: [
      { name: "image", type: "image" },
      { name: "title", label: "Title" },
      { name: "code", label: "Code" },
      { name: "active", label: "Visible", type: "bool" },
    ],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "text", label: "Details", type: "textarea", rows: 3 },
      { name: "code", label: "Offer code (optional)", type: "text" },
      { name: "image", label: "Image", type: "image", required: true },
      { name: "order", label: "Order (lower first)", type: "number", default: 100 },
      { name: "active", label: "Visible on website", type: "boolean", default: true },
    ],
  },
  stores: {
    label: "Stores",
    singular: "Store",
    slugFrom: "name",
    sort: { order: 1, createdAt: 1 },
    columns: [
      { name: "image", type: "image" },
      { name: "name", label: "Name" },
      { name: "hours", label: "Hours" },
      { name: "phones", label: "Phones", type: "list" },
      { name: "active", label: "Visible", type: "bool" },
    ],
    fields: [
      { name: "name", label: "Store name", type: "text", required: true },
      { name: "address", label: "Address", type: "textarea", rows: 2, required: true },
      { name: "hours", label: "Store hours", type: "text", default: "10:30 am to 9:00 pm" },
      { name: "phones", label: "Phone numbers (comma separated)", type: "list" },
      { name: "email", label: "Email", type: "text" },
      { name: "image", label: "Store photo", type: "image", required: true },
      { name: "map", label: "Google Maps link", type: "url", help: "Leave empty to auto-generate from the address." },
      { name: "order", label: "Order (lower first)", type: "number", default: 100 },
      { name: "active", label: "Visible on website", type: "boolean", default: true },
    ],
  },
  pages: {
    label: "Info Pages",
    singular: "Page",
    slugFrom: "title",
    sort: { order: 1, createdAt: 1 },
    columns: [
      { name: "title", label: "Title" },
      { name: "group", label: "Footer group" },
      { name: "active", label: "Visible", type: "bool" },
    ],
    fields: [
      { name: "title", label: "Page title", type: "text", required: true },
      { name: "group", label: "Group (footer column)", type: "select", options: PAGE_GROUPS, default: "Policies" },
      { name: "body", label: "Content", type: "textarea", rows: 12, help: "Separate paragraphs with a blank line." },
      { name: "order", label: "Order inside group (lower first)", type: "number", default: 100 },
      { name: "active", label: "Visible on website", type: "boolean", default: true },
    ],
  },
  faqs: {
    label: "FAQs",
    singular: "FAQ",
    sort: { order: 1, createdAt: 1 },
    columns: [
      { name: "q", label: "Question" },
      { name: "active", label: "Visible", type: "bool" },
    ],
    fields: [
      { name: "q", label: "Question", type: "text", required: true },
      { name: "a", label: "Answer", type: "textarea", rows: 5, required: true },
      { name: "order", label: "Order (lower first)", type: "number", default: 100 },
      { name: "active", label: "Visible on website", type: "boolean", default: true },
    ],
  },
  goldrates: {
    label: "Gold Rates",
    singular: "Rate",
    sort: { order: 1, createdAt: 1 },
    columns: [
      { name: "label", label: "Metal" },
      { name: "price", label: "Price", type: "price" },
      { name: "unit", label: "Unit" },
      { name: "change", label: "Change" },
    ],
    fields: [
      { name: "label", label: "Label (e.g. 22 Karat Gold)", type: "text", required: true },
      { name: "unit", label: "Unit", type: "text", default: "per gram" },
      { name: "price", label: "Price (₹)", type: "number", required: true },
      { name: "change", label: "Change since yesterday (₹, negative for fall)", type: "number", allowNegative: true, default: 0 },
      { name: "order", label: "Order (lower first)", type: "number", default: 100 },
    ],
  },
};

export const settingsFields = [
  { section: "Brand" },
  { name: "siteName", label: "Business name", type: "text", required: true, default: "Sree Sivani Jewellers" },
  { name: "siteUrl", label: "Website address (used in WhatsApp messages)", type: "url", default: "", help: "e.g. https://www.yourdomain.com" },
  { name: "logo", label: "Logo", type: "image", required: true, default: "/logo.jpeg" },
  { name: "metaTitle", label: "Browser / Google title", type: "text", default: "Sree Sivani Jewellers (SSJ) | Jewellery Showroom" },
  { name: "metaDescription", label: "Google description", type: "textarea", rows: 2, default: "Gold, diamond and platinum jewellery from Sree Sivani Jewellers. Consult our experts on WhatsApp." },

  { section: "Contact & WhatsApp" },
  { name: "whatsapp", label: "WhatsApp number (with country code, digits only)", type: "digits", required: true, default: "919346104233", help: "All WhatsApp buttons on the website open a chat with this number." },
  { name: "whatsappCta", label: "WhatsApp button text", type: "text", default: "Enquire on WhatsApp" },
  { name: "phone", label: "Phone number (shown in header & footer)", type: "text", default: "+91 93461 04233" },
  { name: "email", label: "General email", type: "text", default: "care@sreesivanijewellers.com" },
  { name: "emailCorporate", label: "Corporate email", type: "text", default: "b2b@sreesivanijewellers.com" },
  { name: "hours", label: "Customer care hours", type: "text", default: "Mon to Saturday 10AM-6.30PM" },

  { section: "Header" },
  { name: "promoText", label: "Top bar text", type: "text", default: "Save the BIG Joy for later through our Easy Gold Scheme" },
  { name: "promoLinkText", label: "Top bar link text", type: "text", default: "Click for Join Scheme" },
  { name: "promoLinkHref", label: "Top bar link", type: "url", default: "/gold-scheme" },
  { name: "searchHints", label: "Search box hints (comma separated)", type: "list", default: ["Diamond Necklace", "Gold Bangles", "Platinum Ring", "Diamond Earrings", "Mangalsutra"] },

  { section: "Home page banner" },
  { name: "heroTitle", label: "Heading", type: "text", default: "Jewellery that tells your story" },
  { name: "heroText", label: "Sub heading", type: "textarea", rows: 2, default: "Heritage gold, certified diamonds and designs crafted for life's brightest moments." },
  { name: "heroVideo", label: "Background video", type: "video", default: "/media/hero.mp4", help: "MP4 or WebM. Leave empty to use only the image." },
  { name: "heroPoster", label: "Background image", type: "image", default: "/media/hero-poster.jpg" },
  { name: "heroBtn1Text", label: "Button 1 text", type: "text", default: "Shop New Arrivals" },
  { name: "heroBtn1Href", label: "Button 1 link", type: "url", default: "/collections/new-arrivals" },
  { name: "heroBtn2Text", label: "Button 2 text", type: "text", default: "Find a Store" },
  { name: "heroBtn2Href", label: "Button 2 link", type: "url", default: "/stores" },

  { section: "Products" },
  { name: "showPrice", label: "Show prices on the website", type: "boolean", default: true, help: "Turn off to show “Price on request” everywhere and push customers to WhatsApp." },
  { name: "priceNote", label: "Note under product price", type: "text", default: "Inclusive of all taxes. Final price depends on the day's gold rate." },

  { section: "About page" },
  { name: "aboutSub", label: "Banner sub heading", type: "text", default: "World's favourite jeweller" },
  { name: "aboutBanner", label: "Banner image", type: "image", default: "/media/about-1.jpg" },
  { name: "aboutImage", label: "Side image", type: "image", default: "/media/about-2.jpg" },
  { name: "aboutTitle", label: "Heading", type: "text", default: "Crafted with heritage" },
  { name: "aboutBody", label: "Text", type: "textarea", rows: 8, default: "Sree Sivani Jewellers showrooms offer gold, diamond, platinum and precious-stone jewellery, with in-store customisation, expert consultation and easy savings schemes." },
  { name: "aboutFacts", label: "Highlights (one per line: Big text | Small text)", type: "textarea", rows: 5, default: "14 | Stores in Hyderabad\n100% | HUID 916 hallmarked gold\nInsured | Every piece of jewellery\nBuyback | Guaranteed on all gold" },

  { section: "Gold rate page" },
  { name: "goldHistory", label: "22K last 7 days (one per line: Label | Price)", type: "textarea", rows: 7, default: "Today | 7190\nYesterday | 7160\n2 days ago | 7175\n3 days ago | 7120\n4 days ago | 7105\n5 days ago | 7130\n6 days ago | 7090", help: "Rates themselves are edited under “Gold Rates”." },
  { name: "goldNote", label: "Note under rates", type: "text", default: "Rates exclude making charges and GST." },

  { section: "Footer" },
  { name: "newsletterTitle", label: "Newsletter heading", type: "text", default: "Join Our Newsletter Now!" },
  { name: "newsletterText", label: "Newsletter text", type: "text", default: "Be the first to know about new designs, events, and more!" },
  { name: "facebook", label: "Facebook link", type: "url", default: "" },
  { name: "instagram", label: "Instagram link", type: "url", default: "" },
  { name: "twitter", label: "X / Twitter link", type: "url", default: "" },
  { name: "youtube", label: "YouTube link", type: "url", default: "" },
  { name: "copyright", label: "Copyright line", type: "text", default: "© Sree Sivani Jewellers 2026. All rights reserved." },
];

export const settingsDefaults = Object.fromEntries(settingsFields.filter((f) => f.name).map((f) => [f.name, f.default ?? ""]));
